language: java
sudo: required
dist: trusty

jdk:
  - openjdk7
  - openjdk8
  - oraclejdk7
  - oraclejdk8

branches:
  except:
    - /^v|d\d+\.\d+\.\d+$/
    - /^jenkins-veraPDF-rest-v|d\\d+\\.\\d+\\.\\d+$/

after_script:
  - java -jar target/verapdf-rest-0.0.1-SNAPSHOT.jar server  </dev/null &>/dev/null &
  - wget -qO- http://localhost:8080/api
  - wget -qO- http://localhost:8080/api/profiles
  - wget -qO- http://localhost:8080/api/profiles/1b
  - fuser -k 8080/tcp
