name: Test Docker deployment

on:
  workflow_call

jobs:
  test:
    name: Deploy and test image
    runs-on: ubuntu-latest
    steps:
      - name: Test Profiles endpoint
        uses: wei/wget@v1
        with:
          args: -qO- http://verarest:8080/api/profiles
      - name: Test 1B profile endpoint
        uses: wei/wget@v1
        with:
          args: -qO- http://verarest:8080/api/profiles/1b
    services:
      verarest:
        image: ghcr.io/verapdf/verapdf-rest:pr-${{ github.event.pull_request.number }}
        ports:
          - 8080:8080
